runtime: php81
env: flex

# runtime_config:
#   document_root: public

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# env_variables:
#   LOG_CHANNEL: stackdriver
#   APP_KEY: YOUR_APP_KEY
#   APP_STORAGE: /tmp
