runtime: php
env: flex

# runtime_config:
#   document_root: public

automatic_scaling:
  min_idle_instances: automatic
  # max_idle_instances: 1
  # min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 1
#   max_instances: 10

# env_variables:
#   LOG_CHANNEL: stackdriver
#   APP_KEY: YOUR_APP_KEY
#   APP_STORAGE: /tmp
